# 공통 설정
spring.application.name=wino-api

# 프로파일 활성화
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# 동시 세션 1개
security.session.max-sessions=1
# 두 번째 로그인 허용 & 기존 세션 만료
security.session.prevent-second-login=false
